-- ═══════════════════════════════════════════════════════════════════════
-- Cargontainer Marketplace — new-request alerts ("Moje relacije" + Web Push)
--
-- Only adds three tables to the `marketplace` schema; nothing in `public` is
-- touched. Same locks as the base schema: RLS on with no policies, no access
-- for anon/authenticated (only the FastAPI backend, as owner, reads them).
--
-- Rollback:  drop table marketplace.carrier_corridors, marketplace.push_subscriptions,
--            marketplace.push_keys;
-- ═══════════════════════════════════════════════════════════════════════

begin;

create table marketplace.carrier_corridors (
  id                  serial primary key,
  company_id          integer not null,
  origin_country      varchar,            -- ISO-2, null = any
  destination_country varchar,            -- ISO-2, null = any
  both_directions     boolean not null default true,
  created_by          varchar,
  created_at          timestamptz default now()
);
create index on marketplace.carrier_corridors (company_id);

create table marketplace.push_subscriptions (
  id           serial primary key,
  user_id      varchar not null,
  company_id   integer,
  endpoint     varchar not null unique,
  p256dh       varchar not null,
  auth         varchar not null,
  lang         varchar,
  user_agent   varchar,
  created_at   timestamptz default now(),
  last_sent_at timestamptz
);
create index on marketplace.push_subscriptions (user_id);
create index on marketplace.push_subscriptions (company_id);

-- VAPID key pair, generated by the backend on first use (single row id = 1)
create table marketplace.push_keys (
  id              integer primary key,
  private_key_pem varchar not null,
  public_key_b64  varchar not null,
  created_at      timestamptz default now()
);

alter table marketplace.carrier_corridors  enable row level security;
alter table marketplace.push_subscriptions enable row level security;
alter table marketplace.push_keys          enable row level security;

revoke all on marketplace.carrier_corridors, marketplace.push_subscriptions, marketplace.push_keys
  from anon, authenticated;
revoke all on all sequences in schema marketplace from anon, authenticated;

commit;
