"""auto update

Revision ID: 590a5615bbf4
Revises: 506851f0f70a
Create Date: 2026-04-12 23:56:15.830051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590a5615bbf4'
down_revision: Union[str, Sequence[str], None] = '506851f0f70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('offers', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('offers', sa.Column('estimated_days', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('transport_mode', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('carrier_name', sa.String(), nullable=True))
    op.drop_column('offers', 'transit_days')
    op.drop_column('offers', 'operator_name')
    op.drop_column('offers', 'route_details')
    op.drop_column('offers', 'valid_until')
    op.drop_column('offers', 'price_amount')
    op.drop_column('offers', 'terms')
    op.drop_column('offers', 'operator_type')
    op.drop_column('offers', 'price_currency')
    op.add_column('shipments', sa.Column('tracking_number', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('current_location', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('carrier_name', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('estimated_arrival', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('actual_arrival', sa.String(), nullable=True))
    op.alter_column('shipments', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shipments', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shipments', 'current_milestone')
    op.drop_column('shipments', 'operator_name')
    op.drop_column('shipments', 'estimated_delivery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('estimated_delivery', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('operator_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('current_milestone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('shipments', 'actual_arrival')
    op.drop_column('shipments', 'estimated_arrival')
    op.drop_column('shipments', 'carrier_name')
    op.drop_column('shipments', 'current_location')
    op.drop_column('shipments', 'tracking_number')
    op.add_column('offers', sa.Column('price_currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('operator_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('price_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('offers', sa.Column('valid_until', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('route_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('operator_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('transit_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'carrier_name')
    op.drop_column('offers', 'notes')
    op.drop_column('offers', 'transport_mode')
    op.drop_column('offers', 'estimated_days')
    op.drop_column('offers', 'currency')
    op.drop_column('offers', 'price')
    # ### end Alembic commands ###