"""auto update

Revision ID: 5f623620a9d8
Revises: acacb444de61
Create Date: 2026-05-24 13:55:08.775947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f623620a9d8'
down_revision: Union[str, Sequence[str], None] = 'acacb444de61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transport_requests', sa.Column('transport_mode', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('vehicle_type', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('customs_service_type', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('customs_office', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('invoice_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transport_requests', 'invoice_ref')
    op.drop_column('transport_requests', 'customs_office')
    op.drop_column('transport_requests', 'customs_service_type')
    op.drop_column('transport_requests', 'vehicle_type')
    op.drop_column('transport_requests', 'transport_mode')
    # ### end Alembic commands ###