"""auto update

Revision ID: d031d5e4d4f3
Revises: 5fa49900a46d
Create Date: 2026-05-17 01:51:07.723947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd031d5e4d4f3'
down_revision: Union[str, Sequence[str], None] = '5fa49900a46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('shipments', sa.Column('origin_country', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('destination_country', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('transport_category', sa.String(), nullable=True))
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('shipments', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'operational_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('shipments', 'forwarder_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('transport_requests', sa.Column('origin_country', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('destination_country', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('transport_category', sa.String(), nullable=True))
    op.add_column('transport_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('transport_requests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transport_requests', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transport_requests', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transport_requests', 'container_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transport_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.alter_column('transport_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transport_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('transport_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'published'::character varying"),
               nullable=False)
    op.alter_column('transport_requests', 'container_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transport_requests', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transport_requests', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transport_requests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('transport_requests', 'updated_at')
    op.drop_column('transport_requests', 'transport_category')
    op.drop_column('transport_requests', 'destination_country')
    op.drop_column('transport_requests', 'origin_country')
    op.alter_column('shipments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('shipments', 'forwarder_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shipments', 'operational_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'booked'::character varying"),
               nullable=False)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shipments', 'transport_category')
    op.drop_column('shipments', 'destination_country')
    op.drop_column('shipments', 'origin_country')
    op.alter_column('offers', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###